baseURL: /
# baseURL: https://debsahu.github.io/
# baseURL: https://www.debashishsahu.com/
languageCode: en-us
title: Debashish Sahu

theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-73131870-1

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Posts
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
                - name: Github
                  url: "https://www.github.com/debsahu"
                  weight: 20
                - name: YouTube
                  url: "https://www.youtube.com/channel/UC8AWNs6efg2MLhBTuCIJcsg"
                  weight: 20
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Debashish Sahu - Personal Web Parking Location"
    author: Debashish Sahu
    ShowShareButtons: true
    ShowReadingTime: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    defaultTheme: auto
    profileMode:
          enabled: true
          title: "<Title>"
          subtitle: > 
            ### ğŸ§ªğŸ§²NMR/Biophysics Ph. D. ğŸ¥¼Research ğŸ‘¨â€ğŸ”¬Scientist 

            ### ã€½ï¸Amatuer Trader ğŸ›Foodie ğŸ‘¨ğŸ½â€ğŸ’»Coder ğŸ‘¨ğŸ½â€ğŸ”§Tinkerer â–¶ï¸YouTuber
          imageUrl: "deb1.jpg"
          imageTitle: "deb"
          imageWidth: 275
          imageHeight: 275
          buttons:
              - name: Scientific Research
                url: "https://sites.lsa.umich.edu/debsahu/"
              - name: Search
                url: "/search"
              - name: Posts
                url: "/archives"
              - name: Github
                url: "https://www.github.com/debsahu"
              - name: YouTube
                url: "https://www.youtube.com/channel/UC8AWNs6efg2MLhBTuCIJcsg"

    socialIcons:
        - name: "github"
          url: "https://www.github.com/debsahu"
        - name: "youtube"
          url: "https://www.youtube.com/channel/UC8AWNs6efg2MLhBTuCIJcsg"
        - name: "twitter"
          url: "https://twitter.com/debsahu"
        - name: "instagram"
          url: "https://www.instagram.com/debsahu/"
        - name: "facebook"
          url: "https://www.facebook.com/debashish.sahu/"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/debashish-sahu-69234235/"
        - name: "reddit"
          url: "https://www.reddit.com/user/debsahu/"
        - name: "email"
          url: "mailto:debashish.sahu@gmail.com"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

taxonomies:
    category: categories
    tag: tags
    series: series
 
privacy:
    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true